# docker-compose.yml
services:
  motion:
    container_name: guardian-motion
    build:
      context: motion
    networks:
      - guardian
    env_file: .env
    restart: unless-stopped
    volumes:
      - type: bind
        source: /data/guardian/motion
        target: /data
  web:
    container_name: guardian-web
    build:
      context: web
    env_file: .env
    networks:
      - guardian
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /data/guardian/web
        target: /data

networks:
  guardian:
    name: guardian
    ipam:
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
