# docker-compose.yml

services:
  motion:
    container_name: guardian-motion
    build:
      context: motion
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: bind
        source: /data/guardian/motion
        target: /data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian
  web:
    container_name: guardian-web
    build:
      context: web
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian
  nginx:
    container_name: guardian-nginx
    build:
      context: nginx
    restart: unless-stopped
    volumes:
      - type: bind
        source: /data/guardian/motion
        target: /data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian
    ports:
      - "80:80"
  rtsp:
    container_name: guardian-rtsp
    image: aler9/rtsp-simple-server
    restart: unless-stopped
    env_file: .env
    environment:
      RTSP_RTSPADDRESS: "0.0.0.0:554"
      RTSP_RTMPDISABLE: "yes"
      RTSP_HLSDISABLE: "yes"
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian
    ports:
      - "554:554"
  redis:
    container_name: guardian-redis
    image: redis
    restart: unless-stopped
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian
  video-stream-backend:
    container_name: guardian-video-stream-backend
    build:
      context: video_stream_backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian
  audio-stream-backend:
    container_name: guardian-audio-stream-backend
    build:
      context: audio_stream_backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - guardian

networks:
  guardian:
    name: guardian
    ipam:
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
