# docker-compose.yml
services:
  motion:
    container_name: guardian-motion
    build:
      context: motion
    restart: unless-stopped
    env_file: .env
    networks:
      - guardian
    volumes:
      - type: bind
        source: /data/guardian/motion
        target: /data
  web:
    container_name: guardian-web
    build:
      context: web
    restart: unless-stopped
    env_file: .env
    networks:
      - guardian
  nginx:
    container_name: guardian-nginx
    build:
      context: nginx
    restart: unless-stopped
    networks:
      - guardian
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /data/guardian/motion
        target: /data
  rtsp:
    container_name: guardian-rtsp
    image: aler9/rtsp-simple-server
    restart: unless-stopped
    env_file: .env
    environment:
      RTSP_RTSPADDRESS: "0.0.0.0:554"
      RTSP_RTMPDISABLE: "yes"
      RTSP_HLSDISABLE: "yes"
    networks:
      - guardian
    ports:
      - "554:554"

networks:
  guardian:
    name: guardian
    ipam:
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
